set(CMAKE_CXX_COMPILER "g++" CACHE FILEPATH "C++ compiler")
set(CMAKE_C_COMPILER "gcc" CACHE FILEPATH "C compiler")
set(CLANG_TIDY "clang-tidy" CACHE FILEPATH "Clang Tidy binary")
set(CMAKE_CXX_FLAGS_INIT "-fdiagnostics-color=always" CACHE FILEPATH "Default C++ Flags")
set(CMAKE_C_FLAGS_INIT "-fdiagnostics-color=always" CACHE FILEPATH "Default C++ Flags")
